# .streamlit/secrets.toml

[kaggle]
username = "aryanpatelfhdbfj"
key = "9f2639e4747f6271f3702cd3969f93f1"

[twitter]
bearer_token = "AAAAAAAAAAAAAAAAAAAAAIoF3wEAAAAAkKhBzYMZmegOlBZp0f075MvBEiA%3DiRAcUZut1As19bvpKVSzDVe4NXcjlM3lyDTurx54FvXqpPQuaD"